In [238]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [239]:
Train = pd.read_csv("train.csv")
Test = pd.read_csv("test.csv")

In [240]:
Train.shape

(550068, 12)

In [241]:
Test.shape

(233599, 11)

In [242]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
User_ID                       550068 non-null int64
Product_ID                    550068 non-null object
Gender                        550068 non-null object
Age                           550068 non-null object
Occupation                    550068 non-null int64
City_Category                 550068 non-null object
Stay_In_Current_City_Years    550068 non-null object
Marital_Status                550068 non-null int64
Product_Category_1            550068 non-null int64
Product_Category_2            376430 non-null float64
Product_Category_3            166821 non-null float64
Purchase                      550068 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB


In [243]:
Test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233599 entries, 0 to 233598
Data columns (total 11 columns):
User_ID                       233599 non-null int64
Product_ID                    233599 non-null object
Gender                        233599 non-null object
Age                           233599 non-null object
Occupation                    233599 non-null int64
City_Category                 233599 non-null object
Stay_In_Current_City_Years    233599 non-null object
Marital_Status                233599 non-null int64
Product_Category_1            233599 non-null int64
Product_Category_2            161255 non-null float64
Product_Category_3            71037 non-null float64
dtypes: float64(2), int64(4), object(5)
memory usage: 19.6+ MB


In [244]:
Train['Product_Category_3'].unique()

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [245]:
Train['Product_Category_2'][Train['Product_Category_2'].isnull()] = 0
Train['Product_Category_3'][Train['Product_Category_3'].isnull()] = 0
Test['Product_Category_2'][Test['Product_Category_2'].isnull()] = 0
Test['Product_Category_3'][Test['Product_Category_3'].isnull()] = 0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anac

In [246]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
User_ID                       550068 non-null int64
Product_ID                    550068 non-null object
Gender                        550068 non-null object
Age                           550068 non-null object
Occupation                    550068 non-null int64
City_Category                 550068 non-null object
Stay_In_Current_City_Years    550068 non-null object
Marital_Status                550068 non-null int64
Product_Category_1            550068 non-null int64
Product_Category_2            550068 non-null float64
Product_Category_3            550068 non-null float64
Purchase                      550068 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB


In [247]:
Test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233599 entries, 0 to 233598
Data columns (total 11 columns):
User_ID                       233599 non-null int64
Product_ID                    233599 non-null object
Gender                        233599 non-null object
Age                           233599 non-null object
Occupation                    233599 non-null int64
City_Category                 233599 non-null object
Stay_In_Current_City_Years    233599 non-null object
Marital_Status                233599 non-null int64
Product_Category_1            233599 non-null int64
Product_Category_2            233599 non-null float64
Product_Category_3            233599 non-null float64
dtypes: float64(2), int64(4), object(5)
memory usage: 19.6+ MB


In [248]:
Test['Purchase'] = 0

In [249]:
Train['Product_ID'] = Train['Product_ID'].str[1:].astype(int)
Test['Product_ID'] = Test['Product_ID'].str[1:].astype(int)

In [250]:
Total = pd.concat([Train,Test],axis=0)

In [251]:
Total

User_ID  Product_ID Gender    Age  Occupation City_Category  \
0       1000001       69042      F   0-17          10             A   
1       1000001      248942      F   0-17          10             A   
2       1000001       87842      F   0-17          10             A   
3       1000001       85442      F   0-17          10             A   
4       1000002      285442      M    55+          16             C   
5       1000003      193542      M  26-35          15             A   
6       1000004      184942      M  46-50           7             B   
7       1000004      346142      M  46-50           7             B   
8       1000004       97242      M  46-50           7             B   
9       1000005      274942      M  26-35          20             A   
10      1000005      251242      M  26-35          20             A   
11      1000005       14542      M  26-35          20             A   
12      1000005       31342      M  26-35          20             A   
13      1000005      145042      M  26-35          20             A   
14      1000006      231342      F  51-55           9             A   
15      1000006      190242      F  51-55           9             A   
16      1000006       96642      F  51-55           9             A   
17      1000006       58442      F  51-55           9             A   
18      1000007       36842      M  36-45           1             B   
19      1000008      249542      M  26-35          12             C   
20      1000008      220442      M  26-35          12             C   
21      1000008      156442      M  26-35          12             C   
22      1000008      213742      M  26-35          12             C   
23      1000008      214442      M  26-35          12             C   
24      1000008      303442      M  26-35          12             C   
25      1000009      135742      M  26-35          17             C   
26      1000009       39942      M  26-35          17             C   
27      1000009      161442      M  26-35          17             C   
28      1000009       78742      M  26-35          17             C   
29      1000010       85942      F  36-45           1             B   
...         ...         ...    ...    ...         ...           ...   
233569  1005996      184242      F  26-35           0             B   
233570  1005996       45342      F  26-35           0             B   
233571  1006001      124642      F  26-35           7             A   
233572  1006002      121142      M  51-55           0             C   
233573  1006002      233542      M  51-55           0             C   
233574  1006002      226342      M  51-55           0             C   
233575  1006002      284842      M  51-55           0             C   
233576  1006003      313342      F  46-50          17             C   
233577  1006010      223542      M  36-45           0             C   
233578  1006013       20342      F  26-35          20             C   
233579  1006016       14842      M  46-50           1             B   
233580  1006016      109542      M  46-50           1             B   
233581  1006018       71442      M  36-45           1             C   
233582  1006021      112542      M  26-35          12             B   
233583  1006021        3442      M  26-35          12             B   
233584  1006023      262242      M  26-35           0             C   
233585  1006025      161142      F  26-35           1             B   
233586  1006026      110742      M  36-45           6             C   
233587  1006028      162442      M  18-25           4             A   
233588  1006030      129842      M  26-35          17             C   
233589  1006030      241442      M  26-35          17             C   
233590  1006032      252442      M  46-50           7             A   
233591  1006033      127642      M  51-55          13             B   
233592  1006035      135742      F  26-35           1             C   
233593  1006036      255442     

In [252]:
Train.corr(method="pearson")

User_ID  Product_ID  Occupation  Marital_Status  \
User_ID             1.000000   -0.017619   -0.023971        0.020443   
Product_ID         -0.017619    1.000000    0.009344        0.013194   
Occupation         -0.023971    0.009344    1.000000        0.024280   
Marital_Status      0.020443    0.013194    0.024280        1.000000   
Product_Category_1  0.003825    0.090193   -0.007618        0.019888   
Product_Category_2  0.003896   -0.090600    0.006712        0.001099   
Product_Category_3  0.003605   -0.144360    0.012269       -0.004629   
Purchase            0.004716   -0.103961    0.020833       -0.000463   

                    Product_Category_1  Product_Category_2  \
User_ID                       0.003825            0.003896   
Product_ID                    0.090193           -0.090600   
Occupation                   -0.007618            0.006712   
Marital_Status                0.019888            0.001099   
Product_Category_1            1.000000           -0.067877   
Product_Category_2           -0.067877            1.000000   
Product_Category_3           -0.385534            0.094750   
Purchase                     -0.343703            0.052288   

                    Product_Category_3  Purchase  
User_ID                       0.003605  0.004716  
Product_ID                   -0.144360 -0.103961  
Occupation                    0.012269  0.020833  
Marital_Status               -0.004629 -0.000463  
Product_Category_1           -0.385534 -0.343703  
Product_Category_2            0.094750  0.052288  
Product_Category_3            1.000000  0.288501  
Purchase                      0.288501  1.000000

In [253]:
del Total['User_ID']

In [254]:
for i in Train.columns:
    print (Train[i].unique())

[1000001 1000002 1000003 ... 1004113 1005391 1001529]
[ 69042 248942  87842 ... 370293 371644 370853]
['F' 'M']
['0-17' '55+' '26-35' '46-50' '51-55' '36-45' '18-25']
[10 16 15  7 20  9  1 12 17  0  3  4 11  8 19  2 18  5 14 13  6]
['A' 'C' 'B']
['2' '4+' '3' '1' '0']
[0 1]
[ 3  1 12  8  5  4  2  6 14 11 13 15  7 16 18 10 17  9 20 19]
[ 0.  6. 14.  2.  8. 15. 16. 11.  5.  3.  4. 12.  9. 10. 17. 13.  7. 18.]
[ 0. 14. 17.  5.  4. 16. 15.  8.  9. 13.  6. 12.  3. 18. 11. 10.]
[ 8370 15200  1422 ...   135   123   613]


In [255]:
Train = pd.get_dummies(Train)

In [256]:
Train.corr(method='pearson')

User_ID  Product_ID  Occupation  \
User_ID                        1.000000   -0.017619   -0.023971   
Product_ID                    -0.017619    1.000000    0.009344   
Occupation                    -0.023971    0.009344    1.000000   
Marital_Status                 0.020443    0.013194    0.024280   
Product_Category_1             0.003825    0.090193   -0.007618   
Product_Category_2             0.003896   -0.090600    0.006712   
Product_Category_3             0.003605   -0.144360    0.012269   
Purchase                       0.004716   -0.103961    0.020833   
Gender_F                       0.033474   -0.021084   -0.117291   
Gender_M                      -0.033474    0.021084    0.117291   
Age_0-17                      -0.029809    0.000990    0.017627   
Age_18-25                     -0.061903   -0.019640   -0.096659   
Age_26-35                      0.039550   -0.014639   -0.022461   
Age_36-45                      0.010785    0.014153    0.058309   
Age_46-50                      0.028149    0.011393    0.020323   
Age_51-55                     -0.006963    0.012339    0.030846   
Age_55+                       -0.004961    0.013510    0.044096   
City_Category_A               -0.030568   -0.003780   -0.023070   
City_Category_B                0.019688   -0.008863   -0.011673   
City_Category_C                0.008272    0.013068    0.034529   
Stay_In_Current_City_Years_0   0.006495    0.001330   -0.026055   
Stay_In_Current_City_Years_1   0.019574   -0.000236   -0.002092   
Stay_In_Current_City_Years_2   0.018551    0.003490   -0.012716   
Stay_In_Current_City_Years_3  -0.030953   -0.000305    0.025974   
Stay_In_Current_City_Years_4+ -0.019567   -0.004384    0.013905   

                               Marital_Status  Product_Category_1  \
User_ID                              0.020443            0.003825   
Product_ID                           0.013194            0.090193   
Occupation                           0.024280           -0.007618   
Marital_Status                       1.000000            0.019888   
Product_Category_1                   0.019888            1.000000   
Product_Category_2                   0.001099           -0.067877   
Product_Category_3                  -0.004629           -0.385534   
Purchase                            -0.000463           -0.343703   
Gender_F                             0.011603            0.045594   
Gender_M                            -0.011603           -0.045594   
Age_0-17                            -0.139961           -0.013681   
Age_18-25                           -0.189174           -0.035036   
Age_26-35                           -0.027654           -0.018637   
Age_36-45                           -0.013227            0.011429   
Age_46-50                            0.191389            0.025842   
Age_51-55                            0.172278            0.025784   
Age_55+                              0.091778            0.033925   
City_Category_A                     -0.033088            0.015702   
City_Category_B                     -0.001863           -0.006076   
City_Category_C                      0.033661           -0.008554   
Stay_In_Current_City_Years_0        -0.010673            0.004576   
Stay_In_Current_City_Years_1         0.028831            0.006121   
Stay_In_Current_City_Years_2        -0.006474           -0.007000   
Stay_In_Current_City_Years_3        -0.013635           -0.010995   
Stay_In_Current_City_Years_4+       -0.006782            0.006624   

                               Product_Category_2  Product_Category_3  \
User_ID                                  0.003896            0.003605   
Product_ID                              -0.090600           -0.144360   
Occupation                               0.006712            0.012269   
Marital_Status                           0.001099           -0.004629   
Product_Category_1                      -0.067877           -0.385534   
Product_Category_2                       1.000000       

In [257]:
Train['Occupation'] = Train['Occupation'].astype('category')

In [258]:
Train = pd.get_dummies(Train)

In [259]:
Train.corr(method='pearson')

User_ID  Product_ID  Marital_Status  \
User_ID                        1.000000   -0.017619        0.020443   
Product_ID                    -0.017619    1.000000        0.013194   
Marital_Status                 0.020443    0.013194        1.000000   
Product_Category_1             0.003825    0.090193        0.019888   
Product_Category_2             0.003896   -0.090600        0.001099   
Product_Category_3             0.003605   -0.144360       -0.004629   
Purchase                       0.004716   -0.103961       -0.000463   
Gender_F                       0.033474   -0.021084        0.011603   
Gender_M                      -0.033474    0.021084       -0.011603   
Age_0-17                      -0.029809    0.000990       -0.139961   
Age_18-25                     -0.061903   -0.019640       -0.189174   
Age_26-35                      0.039550   -0.014639       -0.027654   
Age_36-45                      0.010785    0.014153       -0.013227   
Age_46-50                      0.028149    0.011393        0.191389   
Age_51-55                     -0.006963    0.012339        0.172278   
Age_55+                       -0.004961    0.013510        0.091778   
City_Category_A               -0.030568   -0.003780       -0.033088   
City_Category_B                0.019688   -0.008863       -0.001863   
City_Category_C                0.008272    0.013068        0.033661   
Stay_In_Current_City_Years_0   0.006495    0.001330       -0.010673   
Stay_In_Current_City_Years_1   0.019574   -0.000236        0.028831   
Stay_In_Current_City_Years_2   0.018551    0.003490       -0.006474   
Stay_In_Current_City_Years_3  -0.030953   -0.000305       -0.013635   
Stay_In_Current_City_Years_4+ -0.019567   -0.004384       -0.006782   
Occupation_0                  -0.006057   -0.002256        0.006910   
Occupation_1                   0.056893   -0.006552        0.043117   
Occupation_2                   0.017432   -0.002180        0.023961   
Occupation_3                  -0.051561   -0.001576        0.001167   
Occupation_4                  -0.015750   -0.013935       -0.110382   
Occupation_5                   0.032789    0.006515       -0.010536   
Occupation_6                   0.026592    0.002824        0.016186   
Occupation_7                   0.012959    0.011345        0.017974   
Occupation_8                  -0.030669    0.001965        0.015479   
Occupation_9                  -0.020688   -0.006750        0.023498   
Occupation_10                 -0.047445    0.000526       -0.110871   
Occupation_11                 -0.018327    0.002151       -0.007730   
Occupation_12                 -0.015302   -0.000481        0.027601   
Occupation_13                 -0.027008    0.010099        0.029281   
Occupation_14                  0.023269   -0.001841        0.001018   
Occupation_15                  0.036969   -0.002054        0.013363   
Occupation_16                  0.005952    0.006688        0.028370   
Occupation_17                  0.000178    0.003999        0.012910   
Occupation_18                  0.006981    0.005312        0.009975   
Occupation_19                 -0.029552   -0.003145       -0.058008   
Occupation_20                 -0.023785    0.001057        0.040947   

                               Product_Category_1  Product_Category_2  \
User_ID                                  0.003825            0.003896   
Product_ID                               0.090193           -0.090600   
Marital_Status                           0.019888            0.001099   
Product_Category_1                       1.000000           -0.067877   
Product_Category_2                      -0.067877            1.000000   
Product_Category_3                      -0.385534            0.094750   
Purchase                                -0.343703            0.052288   
Gender_F                                 0.045594            0.000954   
Gender_M                                -0.045594           -0.000954   
Age_0-17                           

In [260]:
Total['Occupation'] = Total['Occupation'].astype('category')
Total = pd.get_dummies(Total)

In [261]:
Total.shape

(783667, 44)

In [262]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [263]:
783666-233598

550068

In [264]:
Total = Total.reset_index()
del Total['index']

In [289]:
Train = Total[0:550068]
Test = Total[550068:]

In [290]:
Train.shape

(550068, 44)

In [291]:
Test.shape

(233599, 44)

In [292]:
df_y = Train['Purchase']
del Train['Purchase']
df_x = Train

In [293]:
lda = LDA(n_components = None)
lda = lda.fit(df_x,df_y)
df_x = lda.transform(df_x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [294]:
del Test['Purchase']

In [295]:
Test = lda.transform(Test)

In [296]:
from sklearn.model_selection import train_test_split

In [297]:
X_Train,X_Test,Y_Train,Y_Test = train_test_split(df_x,df_y,test_size=0.2,random_state=1)

In [298]:
from sklearn.ensemble import RandomForestRegressor

In [299]:
from sklearn.metrics import r2_score, mean_squared_error
from math import sqrt

In [300]:
rfr = RandomForestRegressor(max_depth=8)
rfr.fit(X_Train,Y_Train)
Y_Pred = rfr.predict(X_Test)
print (sqrt(mean_squared_error(Y_Test,Y_Pred)))
Y_Train_Pred = rfr.predict(X_Train)
print (sqrt(mean_squared_error(Y_Train,Y_Train_Pred)))

2959.621946526783
2946.5207275212765


In [301]:
Y_Final_Pred = rfr.predict(Test)

In [302]:
submission = pd.read_csv('Sample_Submission_Tm9Lura.csv')

In [303]:
submission

Empty DataFrame
Columns: [User_ID, Product_ID, Purchase]
Index: []

In [304]:
Submission_Test = pd.read_csv("test.csv")

In [305]:
submission['User_ID'] = Submission_Test['User_ID']
submission['Product_ID'] = Submission_Test['Product_ID']

In [306]:
Y_Final_Pred.shape

(233599,)

In [311]:
submission['Purchase'] = Y_Final_Pred

In [313]:
submission.to_csv('submission.csv')